
version: "3"

services:
  database:
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "warehouse-db"
    ports:
       - "5432:5432"